name: "Container build and scan"

on:
  push:
    branches:
      - 'master'
permissions: read-all
jobs:
  build-scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: 'service1'
            dockerfile: './service1/Dockerfile'
          - service: 'service2'
            dockerfile: './service2/Dockerfile'
          - service: 'service3'
            dockerfile: './service3/Dockerfile'
    steps:
      - uses: actions/checkout@v4
      - name: "env var: trim owner from repo"
        run: |
          echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | cut -d '/' -f2 )" >> $GITHUB_ENV
      - name: "Build Image - ${{ matrix.service }}"
        run: |
          docker build -t ${{ env.IMAGE_REPOSITORY }}/${{ matrix.service }}:${{ github.sha }} -f ${{ matrix.dockerfile }} .
      - name: "Run Trivy vulnerability scanner"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE_REPOSITORY }}/${{ matrix.service }}:${{ github.sha }}"
          scanners: "vuln,secret,config"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
          hide-progress: false
          format: "sarif"
          output: "trivy-results-${{ matrix.service }}.sarif"
      - name: "Upload Trivy scan results to GitHub Security tab"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results-${{ matrix.service }}.sarif"
